/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsulterLivraison.java
 *
 * Created on 2011-04-09, 13:55:17
 */

package inf5180_jdbc;

import inf5180_jdbc.table.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author woworolandgamy
 */
public class ConsulterLivraison extends javax.swing.JFrame implements ActionListener {


    private String select ;
    private String select2 ;
    
    /** Creates new form ConsulterLivraison */
    public ConsulterLivraison(String nomFenetre) {
        initComponents();
        this.setTitle (nomFenetre) ;
        ajouterEvent () ;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radionumlivraison = new javax.swing.JRadioButton();
        radiodatelivraison = new javax.swing.JRadioButton();
        tnumlivraison = new javax.swing.JTextField();
        tdatelivraison = new javax.swing.JTextField();
        rechercher = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Type de Recherche"));

        radionumlivraison.setText("Numero Livraison");

        radiodatelivraison.setText("Date Livraison");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(radionumlivraison)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 225, Short.MAX_VALUE)
                .add(radiodatelivraison)
                .add(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radionumlivraison)
                    .add(radiodatelivraison))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tnumlivraison.setText("1");

        tdatelivraison.setText("21/12/2010");

        rechercher.setText("Rechercher");

        fermer.setText("FERMER");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NoProduit", "NoCommande", "Codezebre"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .add(fermer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8))
            .add(jPanel1Layout.createSequentialGroup()
                .add(52, 52, 52)
                .add(tnumlivraison, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 153, Short.MAX_VALUE)
                .add(tdatelivraison, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56))
            .add(jPanel1Layout.createSequentialGroup()
                .add(174, 174, 174)
                .add(rechercher, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tnumlivraison, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tdatelivraison, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rechercher)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 294, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(fermer)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fermer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radiodatelivraison;
    private javax.swing.JRadioButton radionumlivraison;
    private javax.swing.JButton rechercher;
    private javax.swing.JTextField tdatelivraison;
    private javax.swing.JTextField tnumlivraison;
    // End of variables declaration//GEN-END:variables

    private javax.swing.ButtonGroup groupeRadio  ;



    public void ajouterEvent () {


        
        groupeRadio = new javax.swing.ButtonGroup () ;
        groupeRadio.add (radionumlivraison) ;
        groupeRadio.add (radiodatelivraison) ;

         radionumlivraison.setSelected (true) ;
         tdatelivraison.setEditable (false) ;

        
         
        rechercher.addActionListener(this);
        fermer.addActionListener(this);
        radionumlivraison.addActionListener(this);
        radiodatelivraison.addActionListener (this) ;
    }

     public void fermerApplication (){

         addWindowListener (new WindowAdapter(){
          public void windowClosing (WindowEvent e) {
            System.exit (0) ;
           }
         }) ;
    }

     
    public void actionPerformed(ActionEvent e) {

        Object source = e.getSource() ;

        if (radionumlivraison.isSelected()){

            tdatelivraison.setEditable (false) ;
            tnumlivraison.setEditable (true) ;

       } else if (radiodatelivraison.isSelected()){
           
           tnumlivraison.setEditable (false) ;
           tdatelivraison.setEditable (true) ;

       }
        
      if (source == rechercher){

          if (radionumlivraison.isSelected()){
                String numLivraison = tnumlivraison.getText() ;
                int valeur ;
                try {
                      valeur = Integer.parseInt (numLivraison) ;
                      if (numLivraison == null || numLivraison.trim().length () == 0 )
                          JOptionPane.showMessageDialog(this, "Donnees invalides", "ERREUR", JOptionPane.ERROR_MESSAGE);
                      else {
                          select = "select noProduit, noCommande qteLivraison from LigneLivraison where noLivraison = " + valeur  ;
                          select2 = "" ;

                          JDBCDriverInformation.unEnonceSQL  = JDBCDriverInformation.con.createStatement() ;
                          ResultSet resultatSelect = JDBCDriverInformation.unEnonceSQL.executeQuery(select) ;
                          
                          int nb = 0 ;
                          java.sql.Statement  unEnonceSQL2 ;

                          ArrayList <ItemLivraison>  listeItem = new ArrayList <ItemLivraison>() ;
                          
                          while (resultatSelect.next()){
                               nb++ ;
                               int numProduit = resultatSelect.getInt("noProduit");
                               int nocommande = resultatSelect.getInt("noCommande");
                               int qtitelivree = resultatSelect.getInt("qteLivraison");

                               select2 = "Select codeZebre from ItemLivraison where noProduit = " + numProduit +
                                       " and  noCommande = " + nocommande + " and noLivraison =  " + valeur ;

                               unEnonceSQL2 =  JDBCDriverInformation.con.createStatement() ;

                                ResultSet resultatSelect2 = unEnonceSQL2.executeQuery(select2) ;
                                if (resultatSelect2.next()){
                                    int codeZebre = resultatSelect2.getInt(1);
                                    ItemLivraison item = new ItemLivraison (codeZebre, numProduit, nocommande, valeur,qtitelivree ) ;
                                    listeItem.add(item);
                                }

                          }

                         if (nb == 0)
                               JOptionPane.showMessageDialog(this, "NUMERO LIVRAISON INEXISTANT", "Information", JOptionPane.INFORMATION_MESSAGE);
                          else{
                             if (listeItem.size() == 0){
                                 JOptionPane.showMessageDialog(this, "Aucune donnée livrée pour cet numero livraison", "Information", JOptionPane.INFORMATION_MESSAGE);
                             }else {
                                 JTableHeader header = jTable1.getTableHeader();
                                 header.setBackground(Color.yellow);

                               
                                for (int i = 0 ; i< listeItem.size() ; i++){

                                   jTable1.getModel().setValueAt(listeItem.get(i).getNoProduit() , i,0);
                                   jTable1.getModel().setValueAt(listeItem.get(i).getNoCommande() , i,1);
                                   jTable1.getModel().setValueAt(listeItem.get(i).getCodeZebre() , i,2);
                                   

                                }
                             }
                          }

                      }

                }catch (NumberFormatException i){
                    
                     JOptionPane.showMessageDialog(this, i.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);

                }catch (SQLException a){
                     JOptionPane.showMessageDialog(this, a.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);

                }

          }else {



          }

      }else if (source == fermer){
         fermerApplication () ;
         this.setVisible (false) ;
      }


        
    }// fin de la methode actionPerformed

}
