/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Payer.java
 *
 * Created on Apr 16, 2011, 7:20:19 PM
 */

package inf5180_jdbc;



import java.sql.SQLException;
import java.sql.ResultSet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;


/**
 *
 * @author H
 */
public class Payer extends javax.swing.JFrame implements ActionListener {

    /** Creates new form Payer */
    public Payer(String nomFenetre) {
        initComponents();
        ajouterEvent();
        this.setTitle (nomFenetre);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textbox_no_cheque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dropdown_carte = new javax.swing.JComboBox();
        radio_cheque = new javax.swing.JRadioButton();
        textbox_no_carte = new javax.swing.JTextField();
        radio_carte = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textbox_banque = new javax.swing.JTextField();
        textbox_no_livraison = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label_statut = new javax.swing.JLabel();
        bouton_payer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textbox_montant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textbox_apres = new javax.swing.JTextField();
        textbox_avant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Identifiant de la banque");

        dropdown_carte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VISA", "Master Card", "American Express" }));
        dropdown_carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_carteActionPerformed(evt);
            }
        });

        radio_cheque.setText("Cheque");
        radio_cheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_chequeActionPerformed(evt);
            }
        });

        radio_carte.setText("Carte de credit");
        radio_carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_carteActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero de la carte");

        jLabel5.setText("Type de carte");

        textbox_no_livraison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_no_livraisonActionPerformed(evt);
            }
        });

        jLabel1.setText("No. de facture ou de livraison");

        label_statut.setText("Solde avant");

        bouton_payer.setText("Effectuer paiment");
        bouton_payer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_payerActionPerformed(evt);
            }
        });

        jLabel7.setText("Montant du paiement");

        textbox_montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_montantActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero de cheque");

        jLabel2.setText("Solde après");

        textbox_apres.setEnabled(false);

        textbox_avant.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textbox_no_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_carte)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(dropdown_carte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textbox_no_carte, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bouton_payer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(28, 28, 28)
                                    .addComponent(textbox_montant, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_cheque)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(textbox_banque, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(textbox_no_cheque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(label_statut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textbox_apres)
                                    .addComponent(textbox_avant, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textbox_no_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_carte)
                            .addComponent(radio_cheque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textbox_banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropdown_carte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textbox_no_carte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textbox_no_cheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textbox_montant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_statut)
                        .addComponent(textbox_avant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_payer)
                    .addComponent(jLabel2)
                    .addComponent(textbox_apres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_carteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dropdown_carteActionPerformed

    private void radio_chequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_chequeActionPerformed
        dropdown_carte.setEnabled(false);
        textbox_no_carte.setEnabled(false);
        textbox_banque.setEnabled(true);
        textbox_no_cheque.setEnabled(true);      
}//GEN-LAST:event_radio_chequeActionPerformed

    private void radio_carteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_carteActionPerformed
        dropdown_carte.setEnabled(true);
        textbox_no_carte.setEnabled(true);
        textbox_banque.setEnabled(false);
        textbox_no_cheque.setEnabled(false);
}//GEN-LAST:event_radio_carteActionPerformed

    private void textbox_no_livraisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_no_livraisonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_textbox_no_livraisonActionPerformed

    private void textbox_montantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_montantActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_textbox_montantActionPerformed

    private void bouton_payerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_payerActionPerformed
       
        try {
            int noLivraison = Integer.parseInt( textbox_no_livraison.getText() );
            float montant = Float.parseFloat( textbox_montant.getText() );

            System.out.println("no livra" + noLivraison);

            if (radio_carte.isSelected()) {
                int no_carte = Integer.parseInt(textbox_no_carte.getText());
                float soldeAvant = trouverSoldeRestant(noLivraison);


                System.out.println("solde avant" + soldeAvant);


                if ( validerMontant(montant, soldeAvant) ) {
                    float soldeApres = soldeAvant - montant;
                    payer( soldeAvant, soldeApres, noLivraison);
                    payerCarteCredit( noLivraison, dropdown_carte.getSelectedItem().toString(), no_carte, montant );
                }                

            } else if ( radio_cheque.isSelected() ) {
                int no_cheque = Integer.parseInt(textbox_no_cheque.getText());
                float soldeAvant = trouverSoldeRestant(noLivraison);


                System.out.println("solde avant" + soldeAvant);

                
                if ( validerMontant(montant, soldeAvant) ) {
                    float soldeApres = soldeAvant - montant;
                    payer( soldeAvant, soldeApres, noLivraison);
                    payerCheque( noLivraison, textbox_banque.getText(), no_cheque, montant );
                }
            }
        }catch (NumberFormatException i){
            JOptionPane.showMessageDialog(this, "Un type de donnée est incorrect!", "ERREUR", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }

    }//GEN-LAST:event_bouton_payerActionPerformed

    

    public void payerCarteCredit(int noLivraison, String typeDeCarte, int noCarte, float montant) throws SQLException {

        JDBCDriverInformation.unEnonceSQL = JDBCDriverInformation.con.createStatement();

        String datePaiement = dateAujourdhui();
        String sql_insert = "INSERT INTO PaiementCarteCredit (noCarte, typeDeCarte, datePaiement, montant, noLivraison)"
                         + " VALUES ('"
                         + String.valueOf(noCarte) + "', '"
                         + typeDeCarte  + "', '"
                         + datePaiement + "', "
                         + montant      + ", "
                         + noLivraison  + ")";

        int rangeesModifiees = JDBCDriverInformation.unEnonceSQL.executeUpdate(sql_insert);
        JDBCDriverInformation.unEnonceSQL.close();        
    }



    public void payerCheque(int noLivraison, String banque, int noCheque, float montant) throws SQLException {

        JDBCDriverInformation.unEnonceSQL = JDBCDriverInformation.con.createStatement();

        String datePaiement = dateAujourdhui();

        Date date = new Date();
        String sql_insert = "INSERT INTO PaiementCheque (noCheque, banque, datePaiement, montant, noLivraison)"
                         + " VALUES ('"
                         + String.valueOf(noCheque) + "', '"
                         + banque       + "', '"
                         + date + "', "
                         + montant      + ", "
                         + noLivraison  + ")";

        int rangeesModifiees = JDBCDriverInformation.unEnonceSQL.executeUpdate(sql_insert);
        JDBCDriverInformation.unEnonceSQL.close();
    }



    public void payer(float soldeAvant, float soldeApres, int noLivraison) throws SQLException {
        
        JDBCDriverInformation.unEnonceSQL = JDBCDriverInformation.con.createStatement();

        String sql_payer = "UPDATE FactureLivraison"
                         + " SET soldeRestant = " + soldeApres
                         + " WHERE noLivraison = " + noLivraison;

        int rangeesModifiees = JDBCDriverInformation.unEnonceSQL.executeUpdate(sql_payer);
        JDBCDriverInformation.unEnonceSQL.close();

        textbox_avant.setText(String.valueOf(soldeAvant));
        textbox_apres.setText(String.valueOf(soldeApres));
    }



    public boolean validerMontant(float montant, float soldeRestant) {
        if ( montant > soldeRestant ) {
            textbox_avant.setText(String.valueOf(soldeRestant));
            textbox_apres.setText("");
            JOptionPane.showMessageDialog(this, "Le montant versé excède le solde restant!", "ERREUR!", JOptionPane.ERROR_MESSAGE);            
            return false;
        } else {
            return true;
        }
    }



    public static float trouverSoldeRestant(int noLivraison) throws SQLException {
        
        JDBCDriverInformation.unEnonceSQL = JDBCDriverInformation.con.createStatement();

        String sql_soldeRestant = "SELECT soldeRestant FROM FactureLivraison WHERE noLivraison = " + noLivraison;

        ResultSet resultatSelect = JDBCDriverInformation.unEnonceSQL.executeQuery(sql_soldeRestant);
        //JDBCDriverInformation.unEnonceSQL.close();

        if ( resultatSelect.next() ) {
            return resultatSelect.getFloat("soldeRestant");
        } else {
            return 6666666;
        }
    }



    public static String dateAujourdhui() {
        // Début du code emprunté
        // http://www.java-tips.org/java-se-tips/java.util/how-to-get-current-date-time.html
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        return dateFormat.format(date);
        // Fin du code emprunté
    }


//    public static Date donneDate(String uneDate) {
//        try{
//        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
//        Date date = new Date();
//        String uneDate = dateFormat.format(date);
//        Date today = dateFormat.parse(uneDate);
//        return today;
//        } catch (ParseException e) {
//            e.printStackTrace();
//        }
//        return null;
//    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_payer;
    private javax.swing.JComboBox dropdown_carte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label_statut;
    private javax.swing.JRadioButton radio_carte;
    private javax.swing.JRadioButton radio_cheque;
    private javax.swing.JTextField textbox_apres;
    private javax.swing.JTextField textbox_avant;
    private javax.swing.JTextField textbox_banque;
    private javax.swing.JTextField textbox_montant;
    private javax.swing.JTextField textbox_no_carte;
    private javax.swing.JTextField textbox_no_cheque;
    private javax.swing.JTextField textbox_no_livraison;
    // End of variables declaration//GEN-END:variables


    
    private javax.swing.ButtonGroup groupeRadio;
    private void ajouterEvent () {
        groupeRadio = new javax.swing.ButtonGroup() ;
        groupeRadio.add (radio_carte);
        groupeRadio.add (radio_cheque);

        radio_carte.addActionListener(this);
        radio_cheque.addActionListener(this);
    }


    
    public void actionPerformed(ActionEvent e) {
    }

    public void fermerApplication (){
        addWindowListener (new WindowAdapter(){
            public void windowClosing (WindowEvent e) {
                System.exit (0) ;
            }
        }) ;
    }
   
}
